name: store_admin_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.2.6

dependencies:
  flutter:
    sdk: flutter
  #  flutter_adaptive_scaffold: ^0.3.1
  flutter_adaptive_scaffold: ^0.1.10+2
  #  printing: ^5.13.4
  printing: ^5.12.0
  #  path_provider: ^2.1.5
  path_provider: ^2.1.4
  #  htmltopdfwidgets: ^1.0.6
  htmltopdfwidgets: ^1.0.3
  #  pdf: ^3.11.1
  pdf: ^3.11.1
  #  audioplayers: ^6.1.0
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/noti_sound.mp3
  fonts:
    - family: NanumGothic
      fonts:
        - asset: fonts/NanumGothic-Regular.ttf
    - family: NotoEmoji
      fonts:
        - asset: fonts/NotoEmoji-VariableFont_wght.ttf
